theme: null

collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title/
  vrecords:
    output: true
    permalink: /vrecords/:title/
  projects:
    output: true
    permalink: /projects/:title/
baseurl: "/8holic"

author:
  name: Bryan Ang
  bio: Student, tech and travel enthuasiast, and aspiring software engineer.