theme: null

collections:
  posts:
    output: true
    permalink: /posts/:title/
  vrecords:
    output: true
    permalink: /vrecords/:title/
  projects:
    output: true
    permalink: /projects/:title/
baseurl: "/8holic"

author:
  name: Your Name
  bio: A short bio